# Generated by Django 4.1.3 on 2022-12-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_address', models.CharField(max_length=100)),
                ('seller_phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('account_holder', models.CharField(max_length=20)),
                ('account_num', models.BigIntegerField()),
                ('ifsc', models.BigIntegerField()),
                ('branch', models.CharField(max_length=30)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
