# Generated by Django 4.1.3 on 2022-12-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_pic',
            field=models.ImageField(upload_to='seller'),
        ),
    ]
